# Generated by Django 5.2.12 on 2026-04-03 11:49

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('required_score', models.IntegerField(help_text='Минимальный балл для достижения этого этапа', verbose_name='Необходимый балл')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Этап',
                'verbose_name_plural': 'Этапы',
                'db_table': 'milestones',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Номер телефона')),
                ('role', models.CharField(choices=[('superuser', 'Супер-пользователь'), ('staff', 'Сотрудник')], default='staff', max_length=50, verbose_name='Роль')),
                ('current_score', models.IntegerField(default=0, verbose_name='Текущий балл')),
                ('is_on_vacation', models.BooleanField(default=False, help_text='Включите, если сотрудник на отпуске или по какой то причине долго не может работать', verbose_name='На отпуске')),
                ('is_active', models.BooleanField(default=True, help_text='Статус активности пользователя, вместо того что бы удалить пользователя, просто отключите эту опцию', verbose_name='Активный')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Суперпользователь')),
                ('is_staff', models.BooleanField(default=False, help_text='Может ли сотрудник заходить в админ панель', verbose_name='Сотрудник')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('current_milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_main.milestone', verbose_name='Текущий этап')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'users',
                'ordering': ['-created'],
                'unique_together': {('first_name', 'last_name', 'middle_name')},
            },
        ),
    ]
