# Generated by Django 5.2.12 on 2026-04-06 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='milestone',
            options={'ordering': ['required_score'], 'verbose_name': 'Этап', 'verbose_name_plural': 'Этапы'},
        ),
        migrations.AddField(
            model_name='milestone',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='FinishedMilestones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_main.milestone', verbose_name='Этап')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Завершенный этап',
                'verbose_name_plural': 'Завершенные этапы',
                'ordering': ['-created'],
            },
        ),
    ]
