# Generated by Django 5.2.12 on 2026-04-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_alter_milestone_options_milestone_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='milestone',
            options={'ordering': ['required_score', 'is_active', '-created'], 'verbose_name': 'Этап', 'verbose_name_plural': 'Этапы'},
        ),
        migrations.AlterField(
            model_name='milestone',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Вместо того, что бы удалить - просто деактивируйте этап', verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Может ли сотрудник создавать и удалять других сотрудников', verbose_name='Суперпользователь'),
        ),
    ]
