# Generated by Django 5.2.12 on 2026-04-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0003_alter_milestone_options_alter_milestone_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_code',
            field=models.CharField(blank=True, help_text='НЕ ЗАПОЛНЯЙТЕ ЭТО ПОЛЕ. Код активации сгенерирутся АВТОМАТИЧЕСКИ', max_length=10, null=True, verbose_name='Код активации'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_activation_code_used',
            field=models.BooleanField(default=False, verbose_name='Использован ли код активации'),
        ),
    ]
