# Generated by Django 5.2.12 on 2026-04-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0004_user_activation_code_user_is_activation_code_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_activation_code_used',
            field=models.BooleanField(default=False, help_text='Индикатор того, использовал ли сотрудник этот код при запуке бота', verbose_name='Использован ли код активации'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Может ли сотрудник заходить в админ панель', verbose_name='Доверенный сотрудник'),
        ),
    ]
