# Generated by Django 5.2.12 on 2026-04-07 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0005_alter_user_is_activation_code_used_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishedmilestones',
            name='milestone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.milestone', verbose_name='Этап'),
        ),
    ]
