# Generated by Django 5.2.12 on 2026-04-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0006_alter_finishedmilestones_milestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Телеграмм ID'),
        ),
    ]
