# Generated by Django 5.2.12 on 2026-04-09 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0008_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='finishedmilestones',
            table='finished_milestones',
        ),
    ]
