# Generated by Django 5.2.12 on 2026-04-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0009_alter_finishedmilestones_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivationalPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.TextField(help_text='Длина не ограничена', verbose_name='мотивирующая фраза')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Мотивирующая фраза',
                'verbose_name_plural': 'Мотивирующие фразы',
                'db_table': 'motivational_phrases',
                'ordering': ['-created'],
            },
        ),
    ]
