# Generated by Django 5.2.12 on 2026-04-10 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0010_motivationalphrase'),
    ]

    operations = [
        migrations.AddField(
            model_name='motivationalphrase',
            name='send_time',
            field=models.TimeField(default='12:00:00', help_text='Если не ставить - то автоматически подставиться 12:00 дня', verbose_name='Время отправки'),
        ),
    ]
