# Generated by Django 5.2.12 on 2026-04-10 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0011_motivationalphrase_send_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='current_milestone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='current_score',
        ),
    ]
