# Generated by Django 5.2.12 on 2026-04-10 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0012_remove_user_current_milestone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Кол-во баллов')),
                ('description', models.CharField(max_length=255, verbose_name='За что сотрудник получает этот балл')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='Укажите сотрудника, кому выдается балл', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Балл',
                'verbose_name_plural': 'Быллы',
                'db_table': 'points',
                'ordering': ['-created'],
            },
        ),
    ]
