# Generated by Django 5.2.12 on 2026-04-10 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0013_point'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='point',
            options={'ordering': ['-created', 'amount'], 'verbose_name': 'Балл', 'verbose_name_plural': 'Быллы'},
        ),
    ]
