# Generated by Django 5.2.12 on 2026-04-11 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0014_alter_point_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motivationalphrase',
            name='send_time',
        ),
    ]
